name: Angular
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy Angular App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Modules
        run: npm ci

      - name: Build Project
        run: npm run build:prod

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Get latest code
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/fr
