name: Angular
on:
  push:
    branches:
      - main
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:

      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Modules
        run: npm ci

      - name: Check code style
        run: npm run lint

      - name: Build Project
        run: npm run build
