name: Generate custom style

on:
  workflow_dispatch:
    inputs:
      primary-color:
        description: 'Primary Color'
        default: ''
        required: true
      version:
        description: 'Version'
        default: '2.2.0'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn add @gouvfr-anct/mediation-numerique

      - name: Main theme color change
        run: |
          cd projects/client-application
          defaultColor=$(grep primary src/scss/variables/_variables.scss)
          newColor='$primary: ${{ github.event.inputs.primary-color }};'
          sed -i "s|$defaultColor|$newColor|g" src/scss/variables/_variables.scss
          defaultMainFontPath=$(grep font-path-main src/scss/variables/_fonts.scss)
          newMainFontPath='$font-path-main: "https://cdn.jsdelivr.net/npm/@gouvfr-anct/cartographie-nationale'@${{ github.event.inputs.version }}'/assets/fonts/";'
          sed -i "s|$defaultMainFontPath|$newMainFontPath|g" src/scss/variables/_fonts.scss
          defaultIconFontPath=$(grep font-path-icons src/scss/variables/_icons.scss)
          newIconFontPath='$font-path-icons: "https://cdn.jsdelivr.net/npm/@gouvfr-anct/cartographie-nationale'@${{ github.event.inputs.version }}'/assets/fonts/";'
          sed -i "s|$defaultIconFontPath|$newIconFontPath|g" src/scss/variables/_icons.scss

      - name: Theme has been changed
        run: echo "La couleur du nouveau thème est ${{ github.event.inputs.primary-color }}"

      - name: Build
        run: |
          yarn build client-application --named-chunks --output-hashing none

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/client-application/styles.css
