# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Primary Color'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Theme has been changed
      run: echo "La couleur du nouveau thème est ${{ github.event.inputs.name }}"
      
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn add @gouvfr-anct/mediation-numerique
      - name: Build
        run: yarn build client-application --named-chunks --output-hashing none

      - name: Add readme, license and package files
        run: |
          mv projects/client-application/README.md dist/client-application/
          mv projects/client-application/LICENSE.md dist/client-application/
          mv projects/client-application/package.json dist/client-application/
      - name: Merge all script files
        run: cat dist/client-application/*.js > dist/client-application/script.js
        
      - name: Replace primary color
        run: sed -i 's/--bs-primary:.*/--bs-primary:${{github.event.inputs.name }}/' *.css

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
