---
name: Release and publish

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Prettier
        run: yarn prettier --check .

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint client-application

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn stylelint "projects/client-application/**/*.scss"

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: |
          cd projects/client-application
          npx commitlint --from origin/main

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn add @gouvfr-anct/mediation-numerique

      - name: Test
        run: yarn test client-application

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project workspace repository
        uses: actions/checkout@v3
        with:
          repository: anct-cartographie-nationale/client-base

      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          path: projects/client-application

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn add @gouvfr-anct/mediation-numerique

      - name: Set fonts paths
        run: |
          cd projects/client-application
          eval PACKAGE_VERSION=$(npm pkg get version)
          defaultMainFontPath=$(grep font-path-main src/scss/variables/_fonts.scss)
          newMainFontPath='$font-path-main: "https://cdn.jsdelivr.net/npm/@gouvfr-anct/cartographie-nationale'@$PACKAGE_VERSION'/assets/fonts/";'
          sed -i "s|$defaultMainFontPath|$newMainFontPath|g" src/scss/variables/_fonts.scss
          defaultIconFontPath=$(grep font-path-icons src/scss/variables/_icons.scss)
          newIconFontPath='$font-path-icons: "https://cdn.jsdelivr.net/npm/@gouvfr-anct/cartographie-nationale'@$PACKAGE_VERSION'/assets/fonts/";'
          sed -i "s|$defaultIconFontPath|$newIconFontPath|g" src/scss/variables/_icons.scss

      - name: Build
        run: yarn build client-application --named-chunks --output-hashing none

      - name: Add readme, license and package files
        run: |
          mv projects/client-application/README.md dist/client-application/
          mv projects/client-application/LICENSE.md dist/client-application/
          mv projects/client-application/package.json dist/client-application/

      - name: Merge all script files
        run: cat dist/client-application/*.js > dist/client-application/script.js

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prettier, eslint, stylelint, commitlint, test, build]

    steps:
      - name: Checkout client-application repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Add readme, license and package files
        run: |
          mv README.md dist/client-application/
          mv LICENSE.md dist/client-application/
          mv package.json dist/client-application/

      - name: Zip release
        run: zip -r release.zip dist/client-application/

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
          scope: '@gouvfr-anct'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: release

      - name: Publish on npm
        run: |
          cd release/client-application/
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
